theme: jekyll-theme-minimal
title:  /// iñaki /<br> san&nbsp;pedro //////
description: I&ntilde;aki San Pedro<br>(/i'ɲakɪ 'sam 'peðro/)
<br><br>
Associate Professor<br>Department of Logic and Theoretical Philosophy<br>Complutense University of Madrid
# logo: isanpedro/arxiu/ventana.jpg