theme: jekyll-theme-minimal
title:  /// iñaki /<br> san&nbsp;pedro //////
description: I&ntilde;aki San Pedro <br> (/i'ɲakɪ 'sam 'peðro/) <br><br> Associate Professor <br> Department of Logic and &nbsp;&nbsp;&nbsp;&nbsp;Theoretical Philosophy <br> Complutense University of Madrid <br><br> Ciudad Universitaria <br> 28040 Madrid <br> Spain <br><br> Tel.&#58; +34 91 394 6054 <br> email&#58; <a href="mailto:isanpedro@ucm.es">isanpedro@ucm.es</a> <br><br> <a href="http://www.ucm.es/isanpedro">View My UCM Webpage</a>

# logo: isanpedro/arxiu/ventana.jpg