theme: jekyll-theme-minimal
title: i&nbsp;&nbsp;ñ&nbsp;&nbsp;a&nbsp;&nbsp;k&nbsp;&nbsp;i&nbsp;&nbsp;s&nbsp;&nbsp;a&nbsp;&nbsp;n&nbsp;&nbsp;p&nbsp;&nbsp;e&nbsp;&nbsp;d&nbsp;&nbsp;r&nbsp;&nbsp;o 
description: Iñaki San Pedro's academic webpage
logo: isanpedro/arxiu/is_ix-transf_01.jpg