theme: jekyll-theme-minimal
title: i&nbsp;&nbsp;ñ&nbsp;&nbsp;a&nbsp;&nbsp;k&nbsp;&nbsp;i&nbsp;&nbsp;s<br><br>a&nbsp;n&nbsp;p&nbsp;e&nbsp;d&nbsp;r&nbsp;o 
description: Iñaki San Pedro's academic webpage
logo: isanpedro/arxiu/is_ix-transf_01.jpg