theme: jekyll-theme-minimal
title: i&nbsp;ñ&nbsp;a&nbsp;k&nbsp;i&nbsp;s&nbsp;a&nbsp;n&nbsp;p&nbsp;e&nbsp;d&nbsp;r&nbsp;o 
description: Iñaki San Pedro's academic webpage
logo: isanpedro/arxiu/is_ix-transf_01.jpg