theme: jekyll-theme-minimal
title:  /// iñaki /<br> san&nbsp;pedro //////
description: I&ntilde;aki San Pedro <br> (/i'ɲakɪ 'sam 'peðro/) <br><br> Associate Professor <br> Department of Logic and &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Theoretical Philosophy <br> Complutense University of Madrid <br><br> Ciudad Universitaria <br> 28040 Madrid <br> Spain <br><br> Tel. +34 943 017424 <br> email <a href="mailto:isanpedro@ucm.es">isanpedro@ucm.es</a>

# logo: isanpedro/arxiu/ventana.jpg