theme: jekyll-theme-minimal
title:  /// iñaki /<br> san&nbsp;pedro //////
description: 
#<body>
I&ntilde;aki San Pedro (/i'ɲakɪ 'sam 'peðro/)
#<br>
#Associate Professor
#<br>
#Department of Logic and Theoretical Philosophy
#<br> 
#Complutense University of Madrid
#</body>
# logo: isanpedro/arxiu/ventana.jpg