theme: jekyll-theme-minimal
title:  /// i ñ a k i s a n p&nbsp;e&nbsp;d&nbsp;r&nbsp;o&nbsp;///
description: <body>I&ntilde;aki San Pedro (/i'ɲakɪ 'sam 'peðro/)</body>
logo: isanpedro/arxiu/ventana_alt.jpg