theme: jekyll-theme-minimal
title:  /// iñaki /<br> san&nbsp;pedro ////// <br><br><br><br><br><br><br><br>
<!--- description: <body>I&ntilde;aki San Pedro (/i'ɲakɪ 'sam 'peðro/)</body>  --->
<!--- logo: isanpedro/arxiu/ventana.jpg --->